sudo: required
services: 
    - docker

before_install:
    - docker build - t tdelclau/react-test -f ./client/Dockerfile.dev ./client 

script:
    - docker run tdelclau/react-test npm test -- --coverage

after_success:
    - docker build -t tdeclau/multi-client ./client
    - docker build -t tdelclau/multi-nginx ./nginx
    - docker build -t tdelclau/multi-server ./server
    - docker build -t tdelclau/mutlti-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push tdelclau/multi-client
    - docker push tdelclau/multi-nginx
    - docker push tdelclau/multi-server
    - docker push tdelclau/multi-worker

    
